# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations
from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel
from typing import Literal
from uuid import UUID


class Problem(BaseModel):
    type: AnyUrl
    title: str
    status: int
    detail: str | None = None
    instance: str | None = None
    code: Literal[
        "invalid_request",
        "text_too_long",
        "unknown_voice",
        "unauthorized",
        "forbidden_scope",
        "quota_exceeded",
        "rate_limited",
        "concurrency_limited",
        "overloaded",
        "job_not_found",
        "idempotency_conflict",
        "internal",
    ] = Field(..., description="Stable machine code")
    request_id: str | None = None


class SynthesisParams(BaseModel):
    cfg_scale: float | None = Field(1.0, ge=1.0, le=3.0)
    audio_temperature: float | None = Field(0.8, ge=0.1, le=1.5)
    audio_topk: int | None = Field(25, ge=1, le=100)
    audio_topp: float | None = Field(0.95, ge=0.1, le=1.0)
    audio_repetition_penalty: float | None = Field(1.2, ge=1.0, le=2.0)


class SynthesizeRequest(BaseModel):
    text: str = Field(..., max_length=3000, min_length=1)
    voice: str | None = "maichi"
    format: Literal["wav", "mp3", "ogg_opus"] | None = "wav"
    sample_rate: Literal[8000, 16000, 24000, 48000] | None = 48000
    normalize: bool | None = True
    params: SynthesisParams | None = None


class JobCreateRequest(BaseModel):
    text: str = Field(..., max_length=100000, min_length=1)
    voice: str | None = "maichi"
    format: Literal["mp3", "ogg_opus", "wav"] | None = "mp3"
    sample_rate: Literal[8000, 16000, 24000, 48000] | None = 48000
    normalize: bool | None = True
    params: SynthesisParams | None = None
    webhook_url: AnyUrl | None = Field(None, description="HTTPS only; public IP only")
    metadata: dict[str, str] | None = Field(None, max_length=10)


class JobStatus(
    RootModel[
        Literal[
            "queued", "segmenting", "synthesizing", "merging", "completed", "failed", "cancelled"
        ]
    ]
):
    root: Literal[
        "queued", "segmenting", "synthesizing", "merging", "completed", "failed", "cancelled"
    ]


class Job(BaseModel):
    id: UUID | None = None
    status: JobStatus | None = None
    total_chars: int | None = None
    segments_total: int | None = None
    segments_done: int | None = None
    output_url: str | None = Field(None, description="Signed URL, valid 24 h")
    duration_ms: int | None = None
    error: str | None = None
    metadata: dict[str, str] | None = None
    created_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class Voice(BaseModel):
    id: str | None = None
    display_name: str | None = None
    gender: str | None = None
    tags: list[str] | None = None
    preview_url: str | None = None


class Scope(RootModel[Literal["synth", "jobs", "usage", "keys"]]):
    root: Literal["synth", "jobs", "usage", "keys"]


class ApiKey(BaseModel):
    id: UUID | None = None
    name: str | None = None
    prefix: str | None = Field(None, description="First 8 chars of the key")
    scopes: list[Scope] | None = None
    store_text: bool | None = None
    created_at: AwareDatetime | None = None
    last_used_at: AwareDatetime | None = None
    revoked_at: AwareDatetime | None = None


class UsageDay(BaseModel):
    day: AwareDatetime
    chars: int
    audio_ms: int
    requests: int
    cache_hits: int


class UsageTotals(BaseModel):
    chars: int
    audio_ms: int
    requests: int
    cache_hits: int


class UsageReport(BaseModel):
    from_: AwareDatetime = Field(..., alias="from")
    to: AwareDatetime
    plan_chars_per_month: int = Field(
        ..., description="The plan's monthly allowance, for comparison with totals.chars."
    )
    days: list[UsageDay] = Field(
        ..., description="One entry per day that had usage; quiet days are omitted."
    )
    totals: UsageTotals
