// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
insert into api_keys (id, tenant_id, name, key_hash, prefix, scopes, store_text)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, tenant_id, name, key_hash, prefix, scopes, store_text, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	KeyHash   []byte
	Prefix    string
	Scopes    []string
	StoreText bool
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.Scopes,
		arg.StoreText,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Scopes,
		&i.StoreText,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one

select k.id, k.tenant_id, k.name, k.key_hash, k.prefix, k.scopes, k.store_text, k.created_at, k.last_used_at, k.revoked_at, t.id, t.plan_id, t.name, t.status, t.created_at, t.updated_at, p.id, p.chars_per_month, p.req_per_minute, p.max_concurrent_streams, p.max_job_chars, p.price_usd_cents, p.overage_usd_per_million
from api_keys k
join tenants t on t.id = k.tenant_id
join plans p on p.id = t.plan_id
where k.key_hash = $1 and k.revoked_at is null
`

type GetAPIKeyByHashRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	KeyHash    []byte
	Prefix     string
	Scopes     []string
	StoreText  bool
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	Tenant     Tenant
	Plan       Plan
}

// API key lookup. The secret is never stored: callers hash it and look up by digest,
// and the comparison happens on the hash (.claude/rules/security.md).
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.Prefix,
		&i.Scopes,
		&i.StoreText,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Tenant.ID,
		&i.Tenant.PlanID,
		&i.Tenant.Name,
		&i.Tenant.Status,
		&i.Tenant.CreatedAt,
		&i.Tenant.UpdatedAt,
		&i.Plan.ID,
		&i.Plan.CharsPerMonth,
		&i.Plan.ReqPerMinute,
		&i.Plan.MaxConcurrentStreams,
		&i.Plan.MaxJobChars,
		&i.Plan.PriceUsdCents,
		&i.Plan.OverageUsdPerMillion,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
select id, tenant_id, name, key_hash, prefix, scopes, store_text, created_at, last_used_at, revoked_at from api_keys
where tenant_id = $1 and (revoked_at is null or $2::bool)
order by created_at desc
`

type ListAPIKeysParams struct {
	TenantID       uuid.UUID
	IncludeRevoked bool
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.TenantID, arg.IncludeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.KeyHash,
			&i.Prefix,
			&i.Scopes,
			&i.StoreText,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
update api_keys set revoked_at = now()
where id = $1 and tenant_id = $2 and revoked_at is null
`

type RevokeAPIKeyParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
update api_keys set last_used_at = now() where id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
