// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package db

import (
	"context"
)

const getCacheEntry = `-- name: GetCacheEntry :one
select cache_key, s3_key, format, duration_ms, bytes, hit_count, created_at, last_hit_at from audio_cache where cache_key = $1
`

func (q *Queries) GetCacheEntry(ctx context.Context, cacheKey []byte) (AudioCache, error) {
	row := q.db.QueryRow(ctx, getCacheEntry, cacheKey)
	var i AudioCache
	err := row.Scan(
		&i.CacheKey,
		&i.S3Key,
		&i.Format,
		&i.DurationMs,
		&i.Bytes,
		&i.HitCount,
		&i.CreatedAt,
		&i.LastHitAt,
	)
	return i, err
}

const touchCacheEntry = `-- name: TouchCacheEntry :exec
update audio_cache set hit_count = hit_count + 1, last_hit_at = now()
where cache_key = $1
`

func (q *Queries) TouchCacheEntry(ctx context.Context, cacheKey []byte) error {
	_, err := q.db.Exec(ctx, touchCacheEntry, cacheKey)
	return err
}

const upsertCacheEntry = `-- name: UpsertCacheEntry :exec

insert into audio_cache (cache_key, s3_key, format, duration_ms, bytes)
values ($1, $2, $3, $4, $5)
on conflict (cache_key) do update set
    s3_key = excluded.s3_key,
    format = excluded.format,
    duration_ms = excluded.duration_ms,
    bytes = excluded.bytes,
    last_hit_at = now()
`

type UpsertCacheEntryParams struct {
	CacheKey   []byte
	S3Key      string
	Format     string
	DurationMs int32
	Bytes      int64
}

// Audio cache catalogue. Redis is the fast index; these rows are what survives a Redis
// flush and what the eviction job scans (FL-07, task 2.8).
func (q *Queries) UpsertCacheEntry(ctx context.Context, arg UpsertCacheEntryParams) error {
	_, err := q.db.Exec(ctx, upsertCacheEntry,
		arg.CacheKey,
		arg.S3Key,
		arg.Format,
		arg.DurationMs,
		arg.Bytes,
	)
	return err
}
