// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :execrows
update jobs set status = 'cancelled', completed_at = now()
where id = $1 and tenant_id = $2
  and status in ('queued', 'segmenting', 'synthesizing', 'merging')
`

type CancelJobParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelJob, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJobSegment = `-- name: ClaimJobSegment :execrows
update job_segments set status = 'running', attempts = attempts + 1
where job_id = $1 and seq = $2 and status in ('pending', 'failed')
`

type ClaimJobSegmentParams struct {
	JobID uuid.UUID
	Seq   int32
}

func (q *Queries) ClaimJobSegment(ctx context.Context, arg ClaimJobSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimJobSegment, arg.JobID, arg.Seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeJob = `-- name: CompleteJob :execrows
update jobs set status = 'completed', output_s3_key = $2, duration_ms = $3, completed_at = now()
where id = $1 and status = 'merging'
`

type CompleteJobParams struct {
	ID          uuid.UUID
	OutputS3Key *string
	DurationMs  *int32
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.OutputS3Key, arg.DurationMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeJobSegment = `-- name: CompleteJobSegment :execrows
with done as (
    update job_segments set status = 'done', s3_key = $3
    where job_id = $1 and seq = $2 and status = 'running'
    returning job_id
)
update jobs set segments_done = segments_done + 1
where id = (select job_id from done)
`

type CompleteJobSegmentParams struct {
	JobID uuid.UUID
	Seq   int32
	S3Key *string
}

func (q *Queries) CompleteJobSegment(ctx context.Context, arg CompleteJobSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJobSegment, arg.JobID, arg.Seq, arg.S3Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnfinishedSegments = `-- name: CountUnfinishedSegments :one
select count(*)::bigint from job_segments where job_id = $1 and status <> 'done'
`

func (q *Queries) CountUnfinishedSegments(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfinishedSegments, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createJob = `-- name: CreateJob :one

insert into jobs (
    id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate,
    normalize, params, total_chars, webhook_url, metadata
) values ($1, $2, $3, $4, 'queued', $5, $6, $7, $8, $9, $10, $11, $12)
returning id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate, normalize, params, total_chars, segments_total, segments_done, output_s3_key, duration_ms, webhook_url, webhook_attempts, metadata, error, created_at, updated_at, completed_at
`

type CreateJobParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ApiKeyID       uuid.UUID
	IdempotencyKey string
	VoiceID        string
	Format         string
	SampleRate     int32
	Normalize      bool
	Params         []byte
	TotalChars     int32
	WebhookUrl     *string
	Metadata       []byte
}

// Jobs and their segments. Every tenant-owned read filters on tenant_id: another
// tenant's job is a 404, not a 403 (docs/07-permissions.md).
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.TenantID,
		arg.ApiKeyID,
		arg.IdempotencyKey,
		arg.VoiceID,
		arg.Format,
		arg.SampleRate,
		arg.Normalize,
		arg.Params,
		arg.TotalChars,
		arg.WebhookUrl,
		arg.Metadata,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.Status,
		&i.VoiceID,
		&i.Format,
		&i.SampleRate,
		&i.Normalize,
		&i.Params,
		&i.TotalChars,
		&i.SegmentsTotal,
		&i.SegmentsDone,
		&i.OutputS3Key,
		&i.DurationMs,
		&i.WebhookUrl,
		&i.WebhookAttempts,
		&i.Metadata,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createJobSegment = `-- name: CreateJobSegment :exec
insert into job_segments (id, job_id, seq, text_hash, chars, status)
values ($1, $2, $3, $4, $5, 'pending')
on conflict (job_id, seq) do nothing
`

type CreateJobSegmentParams struct {
	ID       uuid.UUID
	JobID    uuid.UUID
	Seq      int32
	TextHash []byte
	Chars    int32
}

func (q *Queries) CreateJobSegment(ctx context.Context, arg CreateJobSegmentParams) error {
	_, err := q.db.Exec(ctx, createJobSegment,
		arg.ID,
		arg.JobID,
		arg.Seq,
		arg.TextHash,
		arg.Chars,
	)
	return err
}

const failJob = `-- name: FailJob :execrows
update jobs set status = 'failed', error = $2, completed_at = now()
where id = $1 and status not in ('completed', 'failed', 'cancelled')
`

type FailJobParams struct {
	ID    uuid.UUID
	Error *string
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob, arg.ID, arg.Error)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failJobSegment = `-- name: FailJobSegment :execrows
update job_segments set status = 'failed', last_error = $3
where job_id = $1 and seq = $2
`

type FailJobSegmentParams struct {
	JobID     uuid.UUID
	Seq       int32
	LastError *string
}

func (q *Queries) FailJobSegment(ctx context.Context, arg FailJobSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJobSegment, arg.JobID, arg.Seq, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
select id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate, normalize, params, total_chars, segments_total, segments_done, output_s3_key, duration_ms, webhook_url, webhook_attempts, metadata, error, created_at, updated_at, completed_at from jobs where id = $1 and tenant_id = $2
`

type GetJobParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.TenantID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.Status,
		&i.VoiceID,
		&i.Format,
		&i.SampleRate,
		&i.Normalize,
		&i.Params,
		&i.TotalChars,
		&i.SegmentsTotal,
		&i.SegmentsDone,
		&i.OutputS3Key,
		&i.DurationMs,
		&i.WebhookUrl,
		&i.WebhookAttempts,
		&i.Metadata,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
select id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate, normalize, params, total_chars, segments_total, segments_done, output_s3_key, duration_ms, webhook_url, webhook_attempts, metadata, error, created_at, updated_at, completed_at from jobs where id = $1
`

// The orchestrator has no tenant in hand: it works from a queue entry. Tenant-scoped
// reads stay in GetJob, which is what every API path uses.
func (q *Queries) GetJobByID(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.Status,
		&i.VoiceID,
		&i.Format,
		&i.SampleRate,
		&i.Normalize,
		&i.Params,
		&i.TotalChars,
		&i.SegmentsTotal,
		&i.SegmentsDone,
		&i.OutputS3Key,
		&i.DurationMs,
		&i.WebhookUrl,
		&i.WebhookAttempts,
		&i.Metadata,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
select id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate, normalize, params, total_chars, segments_total, segments_done, output_s3_key, duration_ms, webhook_url, webhook_attempts, metadata, error, created_at, updated_at, completed_at from jobs where tenant_id = $1 and idempotency_key = $2
`

type GetJobByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApiKeyID,
		&i.IdempotencyKey,
		&i.Status,
		&i.VoiceID,
		&i.Format,
		&i.SampleRate,
		&i.Normalize,
		&i.Params,
		&i.TotalChars,
		&i.SegmentsTotal,
		&i.SegmentsDone,
		&i.OutputS3Key,
		&i.DurationMs,
		&i.WebhookUrl,
		&i.WebhookAttempts,
		&i.Metadata,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listJobSegments = `-- name: ListJobSegments :many
select id, job_id, seq, text_hash, chars, status, attempts, s3_key, last_error from job_segments where job_id = $1 order by seq
`

func (q *Queries) ListJobSegments(ctx context.Context, jobID uuid.UUID) ([]JobSegment, error) {
	rows, err := q.db.Query(ctx, listJobSegments, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobSegment{}
	for rows.Next() {
		var i JobSegment
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Seq,
			&i.TextHash,
			&i.Chars,
			&i.Status,
			&i.Attempts,
			&i.S3Key,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
select id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate, normalize, params, total_chars, segments_total, segments_done, output_s3_key, duration_ms, webhook_url, webhook_attempts, metadata, error, created_at, updated_at, completed_at from jobs
where tenant_id = $1 and ($3::timestamptz is null or created_at < $3)
order by created_at desc
limit $2
`

type ListJobsParams struct {
	TenantID uuid.UUID
	Limit    int32
	Before   pgtype.Timestamptz
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.TenantID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ApiKeyID,
			&i.IdempotencyKey,
			&i.Status,
			&i.VoiceID,
			&i.Format,
			&i.SampleRate,
			&i.Normalize,
			&i.Params,
			&i.TotalChars,
			&i.SegmentsTotal,
			&i.SegmentsDone,
			&i.OutputS3Key,
			&i.DurationMs,
			&i.WebhookUrl,
			&i.WebhookAttempts,
			&i.Metadata,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobSegmentsTotal = `-- name: SetJobSegmentsTotal :execrows
update jobs set segments_total = $2, status = 'synthesizing'
where id = $1 and status = 'segmenting'
`

type SetJobSegmentsTotalParams struct {
	ID            uuid.UUID
	SegmentsTotal *int32
}

func (q *Queries) SetJobSegmentsTotal(ctx context.Context, arg SetJobSegmentsTotalParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJobSegmentsTotal, arg.ID, arg.SegmentsTotal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stuckJobs = `-- name: StuckJobs :many
select id, tenant_id, api_key_id, idempotency_key, status, voice_id, format, sample_rate, normalize, params, total_chars, segments_total, segments_done, output_s3_key, duration_ms, webhook_url, webhook_attempts, metadata, error, created_at, updated_at, completed_at from jobs
where status in ('queued', 'segmenting', 'synthesizing', 'merging')
  and updated_at < $1
order by updated_at
limit $2
`

type StuckJobsParams struct {
	UpdatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) StuckJobs(ctx context.Context, arg StuckJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, stuckJobs, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ApiKeyID,
			&i.IdempotencyKey,
			&i.Status,
			&i.VoiceID,
			&i.Format,
			&i.SampleRate,
			&i.Normalize,
			&i.Params,
			&i.TotalChars,
			&i.SegmentsTotal,
			&i.SegmentsDone,
			&i.OutputS3Key,
			&i.DurationMs,
			&i.WebhookUrl,
			&i.WebhookAttempts,
			&i.Metadata,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionJob = `-- name: TransitionJob :execrows
update jobs set status = $3
where id = $1 and status = $2
`

type TransitionJobParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

func (q *Queries) TransitionJob(ctx context.Context, arg TransitionJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionJob, arg.ID, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
