// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Name       string
	KeyHash    []byte
	Prefix     string
	Scopes     []string
	StoreText  bool
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
}

type AudioCache struct {
	CacheKey   []byte
	S3Key      string
	Format     string
	DurationMs int32
	Bytes      int64
	HitCount   int64
	CreatedAt  pgtype.Timestamptz
	LastHitAt  pgtype.Timestamptz
}

type AuditLog struct {
	ID        uuid.UUID
	Actor     string
	Action    string
	Target    *string
	Detail    []byte
	CreatedAt pgtype.Timestamptz
}

type Plan struct {
	ID                   string
	CharsPerMonth        int64
	ReqPerMinute         int32
	MaxConcurrentStreams int32
	MaxJobChars          int32
	PriceUsdCents        int32
	OverageUsdPerMillion pgtype.Numeric
}

type SynthRequest struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ApiKeyID    uuid.UUID
	VoiceID     string
	CacheKey    []byte
	Mode        string
	Chars       int32
	DurationMs  *int32
	TtfaMs      *int32
	Cached      bool
	Status      string
	ErrorCode   *string
	RequestText []byte
	CreatedAt   pgtype.Timestamptz
}

type Tenant struct {
	ID        uuid.UUID
	PlanID    string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Voice struct {
	ID           string
	DisplayName  string
	Gender       *string
	Tags         []string
	ModelVersion string
	TenantID     *uuid.UUID
	Enabled      bool
}
