// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// API key lookup. The secret is never stored: callers hash it and look up by digest,
	// and the comparison happens on the hash (.claude/rules/security.md).
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error)
	GetPlan(ctx context.Context, id string) (Plan, error)
	// Tenant and plan reads. Every tenant-owned query filters on tenant_id; a tenant that is
	// not active must not be served (US-05).
	GetTenant(ctx context.Context, id uuid.UUID) (GetTenantRow, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
