// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
insert into tenants (id, plan_id, name, status)
values ($1, $2, $3, 'active')
returning id, plan_id, name, status, created_at, updated_at
`

type CreateTenantParams struct {
	ID     uuid.UUID
	PlanID string
	Name   string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.PlanID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
select id, chars_per_month, req_per_minute, max_concurrent_streams, max_job_chars, price_usd_cents, overage_usd_per_million from plans where id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.CharsPerMonth,
		&i.ReqPerMinute,
		&i.MaxConcurrentStreams,
		&i.MaxJobChars,
		&i.PriceUsdCents,
		&i.OverageUsdPerMillion,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one

select t.id, t.plan_id, t.name, t.status, t.created_at, t.updated_at, p.id, p.chars_per_month, p.req_per_minute, p.max_concurrent_streams, p.max_job_chars, p.price_usd_cents, p.overage_usd_per_million
from tenants t
join plans p on p.id = t.plan_id
where t.id = $1
`

type GetTenantRow struct {
	ID        uuid.UUID
	PlanID    string
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Plan      Plan
}

// Tenant and plan reads. Every tenant-owned query filters on tenant_id; a tenant that is
// not active must not be served (US-05).
func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (GetTenantRow, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i GetTenantRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Plan.ID,
		&i.Plan.CharsPerMonth,
		&i.Plan.ReqPerMinute,
		&i.Plan.MaxConcurrentStreams,
		&i.Plan.MaxJobChars,
		&i.Plan.PriceUsdCents,
		&i.Plan.OverageUsdPerMillion,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
select id, chars_per_month, req_per_minute, max_concurrent_streams, max_job_chars, price_usd_cents, overage_usd_per_million from plans order by id
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.CharsPerMonth,
			&i.ReqPerMinute,
			&i.MaxConcurrentStreams,
			&i.MaxJobChars,
			&i.PriceUsdCents,
			&i.OverageUsdPerMillion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
