// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const sumCharsByTenantSince = `-- name: SumCharsByTenantSince :many

select tenant_id, sum(chars)::bigint as chars
from synth_requests
where created_at >= $1 and created_at < $2
  and status in ('ok', 'client_cancelled')
group by tenant_id
`

type SumCharsByTenantSinceParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

type SumCharsByTenantSinceRow struct {
	TenantID uuid.UUID
	Chars    int64
}

// Usage reads for quota reconciliation. synth_requests is the system of record; the
// usage_daily rollup arrives with migration 0002 (task 2.1) and can replace this scan
// once it exists.
func (q *Queries) SumCharsByTenantSince(ctx context.Context, arg SumCharsByTenantSinceParams) ([]SumCharsByTenantSinceRow, error) {
	rows, err := q.db.Query(ctx, sumCharsByTenantSince, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumCharsByTenantSinceRow{}
	for rows.Next() {
		var i SumCharsByTenantSinceRow
		if err := rows.Scan(&i.TenantID, &i.Chars); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
