// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertSynthRequest = `-- name: InsertSynthRequest :exec
insert into synth_requests (
    id, tenant_id, api_key_id, voice_id, cache_key, mode, chars,
    duration_ms, ttfa_ms, cached, status, error_code, created_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (id, created_at) do nothing
`

type InsertSynthRequestParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	ApiKeyID   uuid.UUID
	VoiceID    string
	CacheKey   []byte
	Mode       string
	Chars      int32
	DurationMs *int32
	TtfaMs     *int32
	Cached     bool
	Status     string
	ErrorCode  *string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertSynthRequest(ctx context.Context, arg InsertSynthRequestParams) error {
	_, err := q.db.Exec(ctx, insertSynthRequest,
		arg.ID,
		arg.TenantID,
		arg.ApiKeyID,
		arg.VoiceID,
		arg.CacheKey,
		arg.Mode,
		arg.Chars,
		arg.DurationMs,
		arg.TtfaMs,
		arg.Cached,
		arg.Status,
		arg.ErrorCode,
		arg.CreatedAt,
	)
	return err
}

const sumCharsByTenantSince = `-- name: SumCharsByTenantSince :many

select tenant_id, sum(chars)::bigint as chars
from synth_requests
where created_at >= $1 and created_at < $2
  and status in ('ok', 'client_cancelled')
group by tenant_id
`

type SumCharsByTenantSinceParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
}

type SumCharsByTenantSinceRow struct {
	TenantID uuid.UUID
	Chars    int64
}

// Usage reads for quota reconciliation. synth_requests is the system of record; the
// usage_daily rollup arrives with migration 0002 (task 2.1) and can replace this scan
// once it exists.
func (q *Queries) SumCharsByTenantSince(ctx context.Context, arg SumCharsByTenantSinceParams) ([]SumCharsByTenantSinceRow, error) {
	rows, err := q.db.Query(ctx, sumCharsByTenantSince, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumCharsByTenantSinceRow{}
	for rows.Next() {
		var i SumCharsByTenantSinceRow
		if err := rows.Scan(&i.TenantID, &i.Chars); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
