// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listPublicVoices = `-- name: ListPublicVoices :many

select id, display_name, gender, tags, model_version, tenant_id, enabled from voices
where tenant_id is null and enabled
order by id
`

// Voice catalogue. Public presets have tenant_id null; tenant-owned voices are visible
// only to their owner (docs/07-permissions.md, US-13 acceptance criterion 2).
func (q *Queries) ListPublicVoices(ctx context.Context) ([]Voice, error) {
	rows, err := q.db.Query(ctx, listPublicVoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voice{}
	for rows.Next() {
		var i Voice
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Gender,
			&i.Tags,
			&i.ModelVersion,
			&i.TenantID,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoicesForTenant = `-- name: ListVoicesForTenant :many
select id, display_name, gender, tags, model_version, tenant_id, enabled from voices
where enabled and (tenant_id is null or tenant_id = $1)
order by id
`

func (q *Queries) ListVoicesForTenant(ctx context.Context, tenantID *uuid.UUID) ([]Voice, error) {
	rows, err := q.db.Query(ctx, listVoicesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voice{}
	for rows.Next() {
		var i Voice
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Gender,
			&i.Tags,
			&i.ModelVersion,
			&i.TenantID,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVoice = `-- name: UpsertVoice :exec
insert into voices (id, display_name, gender, tags, model_version, tenant_id, enabled)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (id) do update set
    display_name = excluded.display_name,
    model_version = excluded.model_version,
    enabled = excluded.enabled
`

type UpsertVoiceParams struct {
	ID           string
	DisplayName  string
	Gender       *string
	Tags         []string
	ModelVersion string
	TenantID     *uuid.UUID
	Enabled      bool
}

func (q *Queries) UpsertVoice(ctx context.Context, arg UpsertVoiceParams) error {
	_, err := q.db.Exec(ctx, upsertVoice,
		arg.ID,
		arg.DisplayName,
		arg.Gender,
		arg.Tags,
		arg.ModelVersion,
		arg.TenantID,
		arg.Enabled,
	)
	return err
}
