/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/synthesize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize text and return a complete audio file */
        post: operations["synthesize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/synthesize/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesize and stream audio chunks as they are produced
         * @description Returns `Transfer-Encoding: chunked`. For `audio/wav` the RIFF header declares an
         *     unknown length (0xFFFFFFFF). For `audio/ogg` (Opus) pages are emitted per chunk.
         *     Closing the connection cancels inference. Same request body as `/v1/synthesize`.
         *     WebSocket variant: `GET /v1/synthesize/ws` with the same JSON as first message and
         *     binary frames back; text frame `{"type":"end"}` closes; client `{"type":"cancel"}` aborts.
         *
         */
        post: operations["synthesizeStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        /** Create an async synthesis job for long text */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete: operations["cancelJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listVoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKeys"];
        put?: never;
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminCreateTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * @description Stable machine code
             * @enum {string}
             */
            code: "invalid_request" | "text_too_long" | "unknown_voice" | "unauthorized" | "forbidden_scope" | "quota_exceeded" | "rate_limited" | "concurrency_limited" | "overloaded" | "job_not_found" | "idempotency_conflict" | "internal";
            request_id?: string;
        };
        SynthesisParams: {
            /** @default 1 */
            cfg_scale: number;
            /** @default 0.8 */
            audio_temperature: number;
            /** @default 25 */
            audio_topk: number;
            /** @default 0.95 */
            audio_topp: number;
            /** @default 1.2 */
            audio_repetition_penalty: number;
        };
        SynthesizeRequest: {
            text: string;
            /** @default maichi */
            voice: string;
            /**
             * @default wav
             * @enum {string}
             */
            format: "wav" | "mp3" | "ogg_opus";
            /**
             * @default 48000
             * @enum {integer}
             */
            sample_rate: 8000 | 16000 | 24000 | 48000;
            /** @default true */
            normalize: boolean;
            params?: components["schemas"]["SynthesisParams"];
        };
        JobCreateRequest: {
            text: string;
            /** @default maichi */
            voice: string;
            /**
             * @default mp3
             * @enum {string}
             */
            format: "mp3" | "ogg_opus" | "wav";
            /**
             * @default 48000
             * @enum {integer}
             */
            sample_rate: 8000 | 16000 | 24000 | 48000;
            /** @default true */
            normalize: boolean;
            params?: components["schemas"]["SynthesisParams"];
            /**
             * Format: uri
             * @description HTTPS only; public IP only
             */
            webhook_url?: string;
            metadata?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        JobStatus: "queued" | "segmenting" | "synthesizing" | "merging" | "completed" | "failed" | "cancelled";
        Job: {
            /** Format: uuid */
            id?: string;
            status?: components["schemas"]["JobStatus"];
            total_chars?: number;
            segments_total?: number;
            segments_done?: number;
            /** @description Signed URL, valid 24 h */
            output_url?: string | null;
            duration_ms?: number | null;
            error?: string | null;
            metadata?: {
                [key: string]: string;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Voice: {
            id?: string;
            display_name?: string;
            gender?: string;
            tags?: string[];
            preview_url?: string;
        };
        /** @enum {string} */
        Scope: "synth" | "jobs" | "usage" | "keys";
        ApiKey: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @description First 8 chars of the key */
            prefix?: string;
            scopes?: components["schemas"]["Scope"][];
            store_text?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        UsageReport: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /**
             * Format: int64
             * @description The plan's monthly allowance, for comparison with totals.chars.
             */
            plan_chars_per_month: number;
            /** @description One entry per day that had usage; quiet days are omitted. */
            days: components["schemas"]["UsageDay"][];
            totals: components["schemas"]["UsageTotals"];
        };
        UsageDay: {
            /** Format: date-time */
            day: string;
            /** Format: int64 */
            chars: number;
            /** Format: int64 */
            audio_ms: number;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            cache_hits: number;
        };
        UsageTotals: {
            /** Format: int64 */
            chars: number;
            /** Format: int64 */
            audio_ms: number;
            /** Format: int64 */
            requests: number;
            /** Format: int64 */
            cache_hits: number;
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit or quota exceeded */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No worker capacity within the latency budget */
        Overloaded: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    synthesize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesizeRequest"];
            };
        };
        responses: {
            /** @description Audio file */
            200: {
                headers: {
                    "X-Request-Id"?: string;
                    "X-Cache"?: "HIT" | "MISS";
                    "X-Audio-Duration-Ms"?: number;
                    "X-Chars-Billed"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                    "audio/mpeg": string;
                    "audio/ogg": string;
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            402: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Overloaded"];
        };
    };
    synthesizeStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesizeRequest"];
            };
        };
        responses: {
            /** @description Chunked audio stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                    "audio/ogg": string;
                };
            };
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Overloaded"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Job"][];
                        next_cursor?: string | null;
                    };
                };
            };
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Job accepted (or existing job returned for a repeated idempotency key) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            409: components["responses"]["Problem"];
            429: components["responses"]["RateLimited"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job cancelled or already terminal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
    listVoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voice catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voice"][];
                };
            };
        };
    };
    getUsage: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                format?: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageReport"];
                    "text/csv": string;
                };
            };
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keys (prefix only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"][];
                };
            };
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    /** @default [
                     *       "synth"
                     *     ] */
                    scopes?: components["schemas"]["Scope"][];
                    /** @default false */
                    store_text?: boolean;
                };
            };
        };
        responses: {
            /** @description Key created; `secret` is shown exactly once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKey"] & {
                        secret?: string;
                    };
                };
            };
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    plan_id: string;
                };
            };
        };
        responses: {
            /** @description Tenant with first admin key */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready (Postgres */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
